/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pendataan_siswa3;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;


/**
 *
 * @author 1234
 */
public class Form_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Form_Utama
     */
    public Form_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Dasar = new javax.swing.JPanel();
        Panel_Utama = new javax.swing.JPanel();
        Panel_Guru = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableGuru = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addTeacher = new javax.swing.JButton();
        EditOrHapus = new javax.swing.JComboBox<>();
        Panel_Kelas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKelas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        addClass = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        Panel_Siswa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        addStudent = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGuru = new javax.swing.JMenuItem();
        menuKelas = new javax.swing.JMenuItem();
        menuSiswa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Dasar.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout Panel_UtamaLayout = new javax.swing.GroupLayout(Panel_Utama);
        Panel_Utama.setLayout(Panel_UtamaLayout);
        Panel_UtamaLayout.setHorizontalGroup(
            Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Panel_UtamaLayout.setVerticalGroup(
            Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        Panel_Dasar.add(Panel_Utama, "card2");

        tableGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableGuru);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DATA GURU");

        addTeacher.setText("Tambah");
        addTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherActionPerformed(evt);
            }
        });

        EditOrHapus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Edit", "Hapus" }));
        EditOrHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditOrHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_GuruLayout = new javax.swing.GroupLayout(Panel_Guru);
        Panel_Guru.setLayout(Panel_GuruLayout);
        Panel_GuruLayout.setHorizontalGroup(
            Panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(Panel_GuruLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_GuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditOrHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTeacher)
                .addContainerGap())
        );
        Panel_GuruLayout.setVerticalGroup(
            Panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_GuruLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(Panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTeacher)
                    .addComponent(EditOrHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_Dasar.add(Panel_Guru, "card5");

        tableKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableKelas);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("DATA KELAS");

        addClass.setText("Tambah");
        addClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edit", "Hapus" }));

        javax.swing.GroupLayout Panel_KelasLayout = new javax.swing.GroupLayout(Panel_Kelas);
        Panel_Kelas.setLayout(Panel_KelasLayout);
        Panel_KelasLayout.setHorizontalGroup(
            Panel_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(Panel_KelasLayout.createSequentialGroup()
                .addGroup(Panel_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_KelasLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Panel_KelasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addClass)))
                .addContainerGap())
        );
        Panel_KelasLayout.setVerticalGroup(
            Panel_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_KelasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
        );

        Panel_Dasar.add(Panel_Kelas, "card4");

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableSiswa);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("DATA SISWA");

        addStudent.setText("Tambah");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edit", "Hapus" }));

        javax.swing.GroupLayout Panel_SiswaLayout = new javax.swing.GroupLayout(Panel_Siswa);
        Panel_Siswa.setLayout(Panel_SiswaLayout);
        Panel_SiswaLayout.setHorizontalGroup(
            Panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(Panel_SiswaLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel3)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addStudent)
                .addContainerGap())
        );
        Panel_SiswaLayout.setVerticalGroup(
            Panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SiswaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_Dasar.add(Panel_Siswa, "card3");

        jMenu1.setText("Data");

        menuGuru.setText("Data Guru");
        menuGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuruActionPerformed(evt);
            }
        });
        jMenu1.add(menuGuru);

        menuKelas.setText("Data Kelas");
        menuKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKelasActionPerformed(evt);
            }
        });
        jMenu1.add(menuKelas);

        menuSiswa.setText("Data Siswa");
        menuSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSiswaActionPerformed(evt);
            }
        });
        jMenu1.add(menuSiswa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Dasar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel_Dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuruActionPerformed
        Panel_Guru();
    }//GEN-LAST:event_menuGuruActionPerformed

    private void menuKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKelasActionPerformed
        Panel_Kelas();
    }//GEN-LAST:event_menuKelasActionPerformed

    private void menuSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSiswaActionPerformed
        Panel_Siswa();
    }//GEN-LAST:event_menuSiswaActionPerformed

    private void addClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClassActionPerformed

    private void addTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherActionPerformed
        // Tambah Guru
        AddTeacher dialog = new AddTeacher(this, true);
        dialog.setLocationRelativeTo(this); // agar muncul di tengah
        dialog.setVisible(true);
    }//GEN-LAST:event_addTeacherActionPerformed

    private void EditOrHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOrHapusActionPerformed
        // Hapus data
        String selectedAction = (String) EditOrHapus.getSelectedItem();
        
        if ("Hapus".equalsIgnoreCase(selectedAction)) {
            int selectedRow = tableGuru.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus.");
                return;
            }

        int confirm = JOptionPane.showConfirmDialog(null, 
            "Yakin ingin menghapus data ini?", "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
                try {
                    
                    // Ambil ID guru dari kolom pertama (misalnya ID ada di kolom 0)
                    String idGuru = tableGuru.getValueAt(selectedRow, 0).toString();

                    // Buat koneksi dan query DELETE
                    Connection conn = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/pendataan_siswa", "root", "");
                    String sql = "DELETE FROM tbl_guru WHERE id_guru = ?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, idGuru);
                    ps.executeUpdate();
                    
                    // Refresh table
                    loadTableData();

                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                    
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghapus data.");
                }
          }
       }
        //Edit data
        else if ("Edit".equalsIgnoreCase(selectedAction)) { 
                int selectedRow = tableGuru.getSelectedRow();
                if (selectedRow == -1) {
                    JOptionPane.showMessageDialog(null, "Pilih baris yang ingin diedit.");
                    return;
                }
                
                // Ambil data dari tabel
                String id = tableGuru.getValueAt(selectedRow, 0).toString();
                String nama = tableGuru.getValueAt(selectedRow, 1).toString();
                String agama = tableGuru.getValueAt(selectedRow, 2).toString();
                String alamat = tableGuru.getValueAt(selectedRow, 3).toString();
                String jenis_kelamin = tableGuru.getValueAt(selectedRow, 4).toString();
                String no_hp = tableGuru.getValueAt(selectedRow, 5).toString();
                
                //buka dialog
                EditTeacher editDialog = new EditTeacher(this, true); //true = modal
                editDialog.setLocationRelativeTo(this); //tampil di tengah
                editDialog.setData(id, nama, agama, alamat, jenis_kelamin, no_hp);
                
                editDialog.setVisible(true); // <- WAJIB agar dialog muncul
                
                // Refresh tabel setelah dialog ditutup
                loadTableData();

                // Reset comboBox
                EditOrHapus.setSelectedIndex(0);
         }
    }//GEN-LAST:event_EditOrHapusActionPerformed
    
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tableGuru.getModel();
        model.setRowCount(0); // Hapus semua baris
        
        try {
        Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/pendataan_siswa", "root", "");
        String sql = "SELECT * FROM tbl_guru";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
                Object[] row = {
                    rs.getString("id_guru"),
                    rs.getString("nama_guru"),
                    rs.getString("agama"),
                    rs.getString("alamat"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("no_hp"),
                };
                model.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal memuat data.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EditOrHapus;
    private javax.swing.JPanel Panel_Dasar;
    private javax.swing.JPanel Panel_Guru;
    private javax.swing.JPanel Panel_Kelas;
    private javax.swing.JPanel Panel_Siswa;
    private javax.swing.JPanel Panel_Utama;
    private javax.swing.JButton addClass;
    private javax.swing.JButton addStudent;
    private javax.swing.JButton addTeacher;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem menuGuru;
    private javax.swing.JMenuItem menuKelas;
    private javax.swing.JMenuItem menuSiswa;
    private javax.swing.JTable tableGuru;
    private javax.swing.JTable tableKelas;
    private javax.swing.JTable tableSiswa;
    // End of variables declaration//GEN-END:variables

        void panel(){
            Panel_Guru.setVisible(false);
            Panel_Kelas.setVisible(false);
            Panel_Siswa.setVisible(false);
            Panel_Utama.setVisible(false);
        }

        private void Panel_Guru() {
            panel();
            Panel_Guru.setVisible(true);

            String[] judul = {"NIK", "Nama Guru", "Agama", "Alamat", "Jenis Kelamin", "No Telepon"};
            DefaultTableModel tabel = new DefaultTableModel(judul, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Mencegah editing langsung di tabel
                }
            };

            tableGuru.setModel(tabel);
            
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pendataan_siswa", "root", "");
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM tbl_guru");

                while (rs.next()) {
                    String idGuru = rs.getString("id_guru");  // diasumsikan sama dengan NIK
                    String namaGuru = rs.getString("nama_guru");
                    String agama = rs.getString("agama");
                    String alamat = rs.getString("alamat");
                    String jenisKelamin = rs.getString("jenis_kelamin");
                    String noHp = rs.getString("no_hp");

                    String[] data = {idGuru, namaGuru, agama, alamat, jenisKelamin, noHp};
                    tabel.addRow(data);
                }

                rs.close();
                stmt.close();
                conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal memuat data guru:\n" + e.getMessage());
            }

//            int jml = jTable1.getRowCount();
//            for (int i = 0; i < jml; i++) {
//                tabel.removeRow(0);
//            }
        }

        private void Panel_Kelas() {
            panel();
            Panel_Kelas.setVisible(true);

            String[] judul = {"Kode Kelas", "Nama Kelas", "Kode Wali Kelas", "Nama Wali Kelas"};
            DefaultTableModel tabel = new DefaultTableModel(judul, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Supaya data tidak bisa diedit langsung di tabel
                }
            };

            tableKelas.setModel(tabel);
            
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pendataan_siswa", "root", "");
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT k.id_kelas, k.nama_kelas, g.id_guru, g.nama_guru " +
                                 "FROM tbl_kelas k JOIN tbl_guru g ON k.id_guru = g.id_guru");

                while (rs.next()) {
                    String idKelas = rs.getString("id_kelas");  // diasumsikan sama dengan NIK
                    String namaKelas = rs.getString("nama_kelas");
                    String idGuru = rs.getString("id_guru");
                    String namaGuru = rs.getString("nama_guru");

                    String[] data = {idKelas, namaKelas, idGuru, namaGuru};
                    tabel.addRow(data);
                }

                rs.close();
                stmt.close();
                conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal memuat data guru:\n" + e.getMessage());
            }

//            int jml = tableKelas.getRowCount();
//            for (int i = 0; i < jml; i++) {
//                tabel.removeRow(0);
//            }
    }

    private void Panel_Siswa() {
        panel();
        Panel_Siswa.setVisible(true);

        String[] judul = {
            "NIS", "Nama", "Tempat Lahir", "Tanggal Lahir", "Agama",
            "Alamat", "Jenis Kelamin", "No Telepon", "Kelas", "Nama Guru"
        };

        DefaultTableModel tabel = new DefaultTableModel(judul, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tableSiswa.setModel(tabel);

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pendataan_siswa", "root", "");
            Statement stmt = conn.createStatement();

            String query = "SELECT s.nis, s.nama_lengkap, s.tmpt_lhr, s.tgl_lhr, s.agama, " +
                           "s.alamat, s.jenis_kelamin, s.no_hp, k.nama_kelas, g.nama_guru " +
                           "FROM tbl_siswa s " +
                           "JOIN tbl_kelas k ON s.id_kelas = k.id_kelas " +
                           "JOIN tbl_guru g ON k.id_guru = g.id_guru";

            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String nis = rs.getString("nis");
                String nama = rs.getString("nama_lengkap");
                String tempatLahir = rs.getString("tmpt_lhr");
                String tanggalLahir = rs.getString("tgl_lhr");
                String agama = rs.getString("agama");
                String alamat = rs.getString("alamat");
                String jenisKelamin = rs.getString("jenis_kelamin");
                String noHp = rs.getString("no_hp");
                String namaKelas = rs.getString("nama_kelas");
                String namaGuru = rs.getString("nama_guru");

                String[] data = {
                    nis, nama, tempatLahir, tanggalLahir, agama,
                    alamat, jenisKelamin, noHp, namaKelas, namaGuru
                };

                tabel.addRow(data);
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data siswa:\n" + e.getMessage());
        }
    }

}
